# Generated by Django 5.1.2 on 2024-10-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='project',
            name='manufacture',
            field=models.CharField(default='', max_length=250),
        ),
    ]
